### ISSUE TITLE
MELPA release

### ISSUE THREAD

**Issue by mgmarlow** [pimeys/emacs-prisma-mode#12]
Hello! I'd love to use this package, but I don't use doom and I'd like to install w/ `package.el`. I see in #8 that there's been mention of a MELPA release, but I can't find it in the MELPA archives. Have you submitted a PR w/ a recipe already? I'd be happy to submit one myself otherwise.

**Comment by aguynamedben** [comment]
Any plan for this?

**Comment by pimeys** [comment]
No, not really... I'd wish to get the language server support working with eglot and prisma-language-server, and not having a hard dependency to js2- and lsp-modes. Just don't have any time to do that...

**Comment by mgmarlow** [comment]
With Emacs 29 we can just grab the mode directly from the repo using `package-vc-install`:

```elisp
(unless (package-installed-p 'prisma-mode)
  (package-vc-install "https://github.com/pimeys/emacs-prisma-mode"))
```

There's also an upcoming extension to do so from `use-package`:

```elisp
(use-package prisma-mode
  :vc (prisma-mode :url "https://github.com/pimeys/emacs-prisma-mode"))
```

**Comment by skyler544** [comment]
> No, not really... I'd wish to get the language server support working with eglot and prisma-language-server, and not having a hard dependency to js2- and lsp-modes. Just don't have any time to do that...

There's actually nothing to configure in Emacs 29 to make this work except the language server:
1. Globally install the server: `npm install -g @prisma/language-server`
2. Add this to your `init.el`:
```lisp
(use-package prisma-mode
  :ensure t
  :load-path "path to downloaded prisma-mode.el here"
  :config
  (require 'eglot)
  (add-to-list 'eglot-server-programs
               '(prisma-mode "prisma-language-server" "--stdio"))
  :hook (prisma-mode . eglot-ensure))
  ```
  
  That's it! :)
